services:
  api-gateway:
    image: api-gateway:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - TENANT_SERVICE_HOST=tenant-service
      - TENANT_SERVICE_PORT=9000
    depends_on:
      - tenant-service

  tenant-service:
    image: tenant-service:0.1.0-SNAPSHOT
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
